# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  packages: true

warnings_are_errors: true

matrix:
  include:
    - name: "Spark 1.6.3 (R 3.2, openjdk7)"
      r: 3.2
      env:
        - SPARK_VERSION="1.6.3"
        - JAVA_VERSION=openjdk7
    - name: "Spark 2.2.1 (R oldrel, oraclejdk8)"
      r: oldrel
      env:
        - SPARK_VERSION="2.2.1"
        - JAVA_VERSION=oraclejdk8
    - name: "Spark 2.3.2 (R release, oraclejdk8)"
      r: release
      env:
        - SPARK_VERSION="2.3.2"
        - JAVA_VERSION=oraclejdk8
        - CODE_COVERAGE="true"
    - name: "Livy 0.5.0 (R release, oraclejdk8, Spark 2.3.0)"
      r: release
      env:
        - LIVY_VERSION="0.5.0"
        - SPARK_VERSION="2.3.0"
        - JAVA_VERSION=oraclejdk8
    - name: "Arrow (R release, oraclejdk8)"
      r: release
      env:
        - R_ARROW="true"
        - JAVA_VERSION=oraclejdk8
    - name: "Devel (tidyverse, r-lib, forge)"
      env: R_DEVEL_PACKAGES="true"
      r_github_packages:
        - tidyverse/dplyr
        - tidyverse/dbplyr
        - tidyverse/tibble
        - r-lib/rlang
        - rstudio/forge
  allow_failures:
    - env: R_DEVEL_PACKAGES="true"

before_install:
  - jdk_switcher use $JAVA_VERSION
  - echo $JAVA_HOME
  - chmod +x ./ci/arrow.sh
  - if [[ $R_ARROW == "true" ]]; then "./ci/arrow.sh"; fi
  - if [[ $R_ARROW == "true" ]]; then Rscript .travis.R --arrow; fi

script:
  - |
    R CMD build .
    export SPARKLYR_LOG_FILE=/tmp/sparklyr.log
    R CMD check --no-build-vignettes --no-manual --no-tests sparklyr*tar.gz

    if [[ $CODE_COVERAGE == "true" ]]; then
      Rscript .travis.R --coverage
    else
      Rscript .travis.R --testthat
    fi

after_failure:
  - |
    grep -B 10 -A 20 ERROR /tmp/sparklyr.log
